# Step 1: Use an official Python runtime as a parent image
FROM python:3.12-slim

# Step 2: Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Step 3: Set the working directory inside the container
WORKDIR /usr/src/app

# Step 4: Install system dependencies
RUN apt-get update && apt-get install -y \
    libpq-dev gcc python3-dev musl-dev

# Step 5: Install Python dependencies
COPY requirements.txt /usr/src/app/
RUN pip install --no-cache-dir -r requirements.txt

# Step 6: Copy project files to the container
COPY . /usr/src/app/

# Step 7: Expose the port that Django runs on
EXPOSE 8000

# Step 8: Specify the default command to run Django's development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
