# Generated by Django 5.1.1 on 2024-09-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=255)),
                ('length', models.IntegerField()),
                ('lang', models.CharField(max_length=50)),
            ],
        ),
    ]
