# Generated by Django 5.1.1 on 2024-11-24 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_django', '0016_alter_usersocialauth_extra_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='social_django.usersocialauth')),
                ('theme', models.CharField(default='dark', max_length=10)),
                ('font_family', models.CharField(default='VT323', max_length=100)),
                ('font_size', models.CharField(default='40px', max_length=6)),
                ('ultra_wide_config', models.CharField(default='center', max_length=10)),
                ('mode_used', models.CharField(default='time', max_length=10)),
                ('time_selected', models.IntegerField(default=15)),
                ('word_amount_selected', models.IntegerField(default=15)),
                ('challenge_achieved', models.JSONField(default=[0, 0, 0, 0, 0, 0, 0, 0, 0])),
                ('custome_sentence', models.CharField(default='The quick brown fox jumps over the lazy dog.', max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=255)),
                ('length', models.IntegerField()),
                ('lang', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='bsitTypingMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateField(auto_now=True)),
                ('test_time', models.IntegerField(default=15)),
                ('test_ammount', models.IntegerField(default=0)),
                ('is_started', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_django.usersocialauth')),
            ],
        ),
        migrations.CreateModel(
            name='bsitTypeingMasterPlayers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_django.usersocialauth')),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='type_master.bsittypingmaster')),
            ],
        ),
        migrations.CreateModel(
            name='TestHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wpm', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('cormisex', models.CharField(max_length=20)),
                ('mode', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=20)),
                ('bpr', models.BooleanField(default=False)),
                ('test_taken', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_django.usersocialauth')),
            ],
        ),
    ]
