# Generated by Django 5.1.1 on 2024-09-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='special_charact',
            field=models.BooleanField(default=False),
        ),
    ]
