# Generated by Django 5.1.1 on 2024-12-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type_master', '0002_bsittypeingmasterplayers_is_can_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='exp',
            field=models.IntegerField(default=0),
        ),
    ]
