# Generated by Django 5.1.1 on 2024-09-14 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('type_master', '0002_word_special_charact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='special_charact',
        ),
    ]
