# Generated by Django 5.1.1 on 2024-12-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type_master', '0003_usersettings_exp'),
    ]

    operations = [
        migrations.CreateModel(
            name='achivement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
