# Generated by Django 5.1.1 on 2024-12-07 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('type_master', '0004_achivement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achivement',
            name='is_done',
        ),
    ]
