# Generated by Django 5.1.1 on 2024-10-28 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('type_master', '0004_usersettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
