# Generated by Django 5.1.1 on 2024-12-07 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0016_alter_usersocialauth_extra_data'),
        ('type_master', '0005_remove_achivement_is_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerAchivements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_done', models.DateField(auto_now=True)),
                ('achivement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='type_master.achivement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_django.usersocialauth')),
            ],
        ),
    ]
