# Generated by Django 5.1.1 on 2024-10-28 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0016_alter_usersocialauth_extra_data'),
        ('type_master', '0005_delete_usersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='social_django.usersocialauth')),
                ('theme', models.CharField(default='dark', max_length=10)),
            ],
        ),
    ]
