# Generated by Django 5.1.1 on 2024-10-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type_master', '0006_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='challenge_achieved',
            field=models.JSONField(default=[0, 0, 0, 0, 0, 0, 0, 0, 0]),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='custome_sentence',
            field=models.CharField(default='The quick brown fox jumps over the lazy dog.', max_length=255),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='mode_used',
            field=models.CharField(default='time', max_length=10),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='time_selected',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='word_amount_selected',
            field=models.IntegerField(default=15),
        ),
    ]
