# Generated by Django 5.1.1 on 2024-12-31 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type_master', '0006_playerachivements'),
    ]

    operations = [
        migrations.AddField(
            model_name='achivement',
            name='achivement_image',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
    ]
