# Generated by Django 5.1.1 on 2024-10-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type_master', '0007_usersettings_challenge_achieved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='challenge_achieved',
            field=models.JSONField(default=list),
        ),
    ]
