# Generated by Django 5.1.1 on 2024-10-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type_master', '0008_alter_usersettings_challenge_achieved'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
