# Generated by Django 5.1.1 on 2024-10-30 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type_master', '0009_usersettings_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wpm', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('cormisex', models.CharField(max_length=20)),
                ('mode', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=20)),
                ('bpr', models.BooleanField(default=False)),
                ('test_taken', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='type_master.usersettings')),
            ],
        ),
    ]
