# Generated by Django 5.1.1 on 2024-10-30 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0016_alter_usersocialauth_extra_data'),
        ('type_master', '0010_testhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_django.usersocialauth'),
        ),
    ]
