# Generated by Django 5.1.1 on 2024-11-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type_master', '0011_alter_testhistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='challenge_achieved',
            field=models.JSONField(default=[0, 0, 0, 0, 0, 0, 0, 0, 0]),
        ),
    ]
