# Generated by Django 5.1.1 on 2024-11-03 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type_master', '0012_alter_usersettings_challenge_achieved'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='ultra_wide_config',
            field=models.CharField(default='center', max_length=10),
        ),
    ]
