# Generated by Django 5.1.1 on 2024-11-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type_master', '0013_usersettings_ultra_wide_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='font_size',
            field=models.CharField(default='40px', max_length=6),
        ),
    ]
