# Generated by Django 5.1.1 on 2024-11-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type_master', '0014_usersettings_font_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='font_family',
            field=models.CharField(default='VT323', max_length=100),
        ),
    ]
